name: Mirror to Private Repo

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      target_repo:
        description: 'Target repository'
        required: true
        default: 'gitsteves/weekly-trader'
      branch:
        description: 'Branch to push to'
        required: true
        default: 'main'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Push to private mirror
      run: |
        git remote add mirror https://$GH_PAT@github.com/${{ github.event.inputs.target_repo }}.git
        git push mirror --mirror
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
